### ISSUE TITLE
Que tam um slack?

### ISSUE THREAD

**Issue by odirleiborgert** [svelte-brasil/forum#1]
Que tam um slack?

**Comment by ktquez** [comment]
@odirleiborgert E ai man tudo certo?

Como a comunidade ainda está começando, tem pouca gente nos outros canais.

Convido você se quiser fazer parte nesse começo, o mock (desenho) do site está quase pronto para desenvolvermos o site do Svelte Brasil.

Depois do site pronto e com os primeiros conteúdos saindo creio que a divulgação será mais ampla e os canais começarão a ficar movimentados.

---

### Telegram
- https://t.me/sveltebrasil

### Facebook Group
- https://www.facebook.com/groups/sveltebrasil/

### Twitter
- https://twitter.com/sveltebrasil

### Youtube
- https://www.youtube.com/channel/UCp8jamqJRGg86eMnewxjWng

### Slack
- http://bit.ly/svelte-brasil-slack
